using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
[assembly: AssemblyTitle("ToolKit.Data.MongoDb")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyProduct("ToolKit.Data.MongoDb")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("45e88f4d-9e50-40f2-93ef-07439952f6fc")]
