image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build_script:
  - ps: .\build.ps1

test: off

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
