image: Visual Studio 2019

build_script:
  - ps: .\build.ps1 #-Target AppVeyor

test: off

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

cache:
- tools -> build.cake, tools/packages.config

