image: Visual Studio 2019

environment_variables:
  CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECK: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build_script:
  - ps: .\build.ps1

test: off

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

cache:
- tools -> build.cake, tools/packages.config

